# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: "Docker Buildx Bake"
description: "GitHub Action to use Docker Buildx Bake as a high-level build command"
author: 'docker'
branding:
  icon: 'anchor'
  color: 'blue'

inputs:
  builder:
    description: "Builder instance"
    required: false
  workdir:
    description: "Working directory of bake execution"
    required: false
    default: '.'
  source:
    description: "Context to build from. Can be either local or a remote bake definition"
    required: false
  allow:
    description: "Allow build to access specified resources (e.g., network.host)"
    required: false
  call:
    description: "Set method for evaluating build (e.g., check)"
    required: false
  files:
    description: "List of bake definition files"
    required: false
  no-cache:
    description: "Do not use cache when building the image"
    required: false
    default: 'false'
  pull:
    description: "Always attempt to pull a newer version of the image"
    required: false
    default: 'false'
  load:
    description: "Load is a shorthand for --set=*.output=type=docker"
    required: false
    default: 'false'
  provenance:
    description: "Provenance is a shorthand for --set=*.attest=type=provenance"
    required: false
  push:
    description: "Push is a shorthand for --set=*.output=type=registry"
    required: false
    default: 'false'
  sbom:
    description: "SBOM is a shorthand for --set=*.attest=type=sbom"
    required: false
  set:
    description: "List of targets values to override (eg. targetpattern.key=value)"
    required: false
  targets:
    description: "List of bake targets"
    required: false
  github-token:
    description: "API token used to authenticate to a Git repository for remote definitions"
    default: ${{ github.token }}
    required: false

outputs:
  metadata:
    description: 'Build result metadata'

runs:
  using: 'node20'
  main: 'dist/index.js'
  post: 'dist/index.js'
