name: ci-subaction

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'
  push:
    branches:
      - 'master'
      - 'releases/v*'
    tags:
      - 'v*'
    paths:
      - '.github/workflows/ci-subaction.yml'
      - 'subaction/**'
      - 'test/**'
  pull_request:
    paths:
      - '.github/workflows/ci-subaction.yml'
      - 'subaction/**'
      - 'test/**'

jobs:
  list-targets:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          -
            testdir: group
          -
            testdir: group-matrix
            target: validate
          -
            testdir: multi-files
            files: |
              docker-bake.json
              docker-bake.hcl
    steps:
      -
        name: Checkout
        uses: actions/checkout@v5
      -
        name: Matrix gen
        id: gen
        uses: ./subaction/list-targets
        with:
          workdir: ./test/${{ matrix.testdir }}
          files: ${{ matrix.files }}
          target: ${{ matrix.target }}

  matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          -
            testdir: group
          -
            testdir: group-matrix
            target: validate
          -
            testdir: group-with-platform
            target: validate
          -
            testdir: group-with-platform
            target: validate
            fields: platforms
          -
            testdir: group-with-platform
            target: validate
            fields: platforms,dockerfile
    steps:
      -
        name: Checkout
        uses: actions/checkout@v5
      -
        name: Matrix gen
        id: gen
        uses: ./subaction/matrix
        with:
          workdir: ./test/${{ matrix.testdir }}
          target: ${{ matrix.target }}
          fields: ${{ matrix.fields }}
